### ISSUE TITLE
MCRPlanner.cpp use-demo

### ISSUE THREAD

**Issue by yousiri** [krishauser/KrisLibrary#13]
Recently  I am studying MCR issues and find the source code here, but I do not know how to use the MCRPlanner. How to define the movable obstacle and the immovable obstacle? can you provide me a demo for it?  thank you

**Comment by krishauser** [comment]
The obstacles are defined by CSpace::AddConstraint.  You may define movable / immovable obstacles by using the MCRPlanner::obstacleWeight vector.  Resize this to the number of constraints in your CSpace, and set the weight for all immovable obstacles to infinity and all movable obstacles to 1.
