### ISSUE TITLE
PointCloud is slow in initializing octree

### ISSUE THREAD

**Issue by patricknaughton01** [krishauser/KrisLibrary#15]
Klampt's vis.debug() of a PointCloud is very slow on rendering. I was able to trace down the problem to octree->Add() in the https://github.com/krishauser/KrisLibrary/blob/master/geometry/CollisionPointCloud.cpp#L30

In the for loop when looping through all the points, the total time spent in initializing an octree containing 640*480 points is about 90 seconds on the laptop from our lab, and it is eating 100% cpu which makes the program not responding.

I will attach an minimal example that can reproduce the issue.
[example_script_to_reproduce.zip](https://github.com/krishauser/KrisLibrary/files/5668230/example_script_to_reproduce.zip)

Edit: Just realized Patrick forget to log out on the lab computer

**Comment by krishauser** [comment]
The newest version of Klampt 0.8.4 (up to date with master / devel) doesn't perform the collision initialization, so this example should be fixed.

However, the collision initialization is really a problem when there are 10k+ points all coincident (missing data being treated as (0,0,0)).  There's a stupid N^2 loop in this case that just kills the progress. I just pushed a fix to KrisLibrary (master / devel) that fixes this problem, and now my computer completes the octree initialization in 0.15s.
