### ISSUE TITLE
GLDraw::GeometryAppearance.ModulateColor used in Klampt 0.9 Interface

### ISSUE THREAD

**Issue by ShaoxiongYao** [krishauser/KrisLibrary#23]
I am building Klampt 0.9 from source and line 159 in `Cpp/Interface/RobotTestGUI.cpp` called `app.ModulateColor(blue,0.5);`. But in the latest `devel` branch, `GLDraw::GeometryAppearance.ModulateColor` has been commented out. I wonder if we should use `SetTintColor` in Klampt or add this function back to the `devel` branch.

**Comment by krishauser** [comment]
Should be fixed now.
