### ISSUE TITLE
Typo in optimization/GLPKInterface.cpp

### ISSUE THREAD

**Issue by ShaoxiongYao** [krishauser/KrisLibrary#24]
On `devel` branch, line 17 currently is:
`#if GLP_MAJOR_VERSION < 4 || (GLP_MAJOR_VERSION == 4 && GLP_MINOR_VERSION < 20)`
There should be a typo in `GPL_MINOR_VERSION`, it should be `GLP_MINOR_VERSION`.

**Comment by krishauser** [comment]
Fixed.
